# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '55 22 * * *'
    - cron: '30 23 * * *'
    - cron: '55 23 * * *'
    - cron: '10 5 * * *'
    - cron: '10 6 * * *' 
    - cron: '10 7 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:  windows-2019

    steps:
      
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          
      - name: CI
        run: python main.py

         
